import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import {
  FileText,
  Download,
  Printer,
  CheckCircle2,
  ShieldCheck,
  Sparkles,
  FolderLock,
  ChevronDown,
  QrCode,
  Scale,
  Phone,
  Mail,
  CreditCard,
  Globe,
  Receipt,
  FileCheck,
} from 'lucide-react';

interface CourtReportGeneratorProps {
  initialCaseId?: string;
}

export const CourtReportGenerator: React.FC<CourtReportGeneratorProps> = ({
  initialCaseId,
}) => {
  const { cases, currentUser } = useApp();

  const [selectedCaseId, setSelectedCaseId] = useState<string>(
    initialCaseId || cases[0]?.id || 'CASE-1024'
  );

  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [isDownloading, setIsDownloading] = useState<boolean>(false);
  const [isCopied, setIsCopied] = useState<boolean>(false);
  const [activeWatermark, setActiveWatermark] = useState<boolean>(true);
  const [includeChainOfCustody, setIncludeChainOfCustody] =
    useState<boolean>(true);
  const [includeAIConfidence, setIncludeAIConfidence] =
    useState<boolean>(true);

  const activeCase = cases.find((c) => c.id === selectedCaseId) ||
    cases[0] || {
      id: 'CASE-1024',
      title: 'Phishing Campaign & Financial Fraud',
      victimName: 'Alex Rivera',
      victimContact: 'alex.rivera@example.com',
      category: 'Phishing / Financial Scam',
      status: 'Under Investigation',
      urgency: 'Critical',
      dateSubmitted: '2026-08-04 14:32:00',
      lossAmount: '₹25,000',
      description:
        'Victim received an automated SMS claiming bank account suspension. Clicked spoofed link and lost funds via unauthorized IMPS transfer.',
    };

  /*
   * Safely resolve the incident date without assuming that every CaseItem
   * contains the same date property.
   */
  const getIncidentDate = (): string => {
    if ('incidentDate' in activeCase && activeCase.incidentDate) {
      return String(activeCase.incidentDate);
    }

    if ('reportedDate' in activeCase && activeCase.reportedDate) {
      return String(activeCase.reportedDate);
    }

    if ('dateSubmitted' in activeCase && activeCase.dateSubmitted) {
      return String(activeCase.dateSubmitted);
    }

    return 'Not Available';
  };

  const incidentDate = getIncidentDate();

  const officerName =
    currentUser?.name || 'Inspector Vikramaditya Sen';
  const officerBadge =
    currentUser?.badgeId || 'OFF-8842';
  const officerBureau =
    currentUser?.department || 'Cyber Crime Cell, Zone 4';

  const handleGeneratePDF = () => {
    setIsGenerating(true);

    setTimeout(() => {
      setIsGenerating(false);
    }, 1200);
  };

  const handleDownload = () => {
    setIsDownloading(true);

    setTimeout(() => {
      setIsDownloading(false);

      const reportText = `
FORENSIQ CYBERCRIME INVESTIGATION REPORT
========================================
Case ID: ${activeCase.id}
Investigation Officer: ${officerName} (${officerBadge})
Victim: ${activeCase.victimName} (${activeCase.victimContact || 'N/A'})
Crime Type: ${activeCase.category}
Incident Date: ${incidentDate}
Financial Loss: ${activeCase.lossAmount || '₹25,000'}

1. CASE SUMMARY:
${activeCase.description}

2. VICTIM INFORMATION:
Name: ${activeCase.victimName}
Email/Contact: ${activeCase.victimContact || 'N/A'}
Status: Verified Complainant under Section 66D IT Act

3. SUSPECT INFORMATION:
Suspect Alias: @ShadowOperator (Telegram Syndicate)
Real Name / Primary Mule: Vikram Malhotra / Rajesh Kumar
IP Address: 185.220.101.5 (Tor Exit Node)
Mule Account: ACC-9048-2819-5501 (Axis Bank)

4. EVIDENCE LIST:
- EVID-101: Phishing SMS Screenshot & Payload URL (SHA-256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)
- EVID-102: IMPS Transaction Receipt TXN-8849201948 (SHA-256: 7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284ddd200126d9069e)

5. SHA-256 HASHES:
- Cryptographic Proof Chain Intact and Verified against Blockchain Ledger.

6. EXTRACTED ENTITIES:
- Phone: +91 98765 43210 (Shared across Case #1024, #1089)
- UPI VPA: paym-fraudster@okaxis
- Bank Account: ACC-9048-2819-5501

7. INVESTIGATION TIMELINE:
- 2026-08-04 14:32:00: Complaint Logged
- 2026-08-04 15:10:00: Forensic Evidence Ingested
- 2026-08-05 09:30:00: Financial Freeze Subpoena Issued

8. AI ANALYSIS:
ForensIQ Threat Confidence: 98.4% Match with Organized Cybercrime Syndicate.

9. RELATED CASES:
- Case #1089 (Identity Theft)
- Case #2048 (Investment Fraud)

10. APPLICABLE LEGAL SECTIONS:
- Section 66D IT Act (Cheating by personation)
- Section 66C IT Act (Identity Theft)
- BNS 318(4) / IPC 420 (Cheating)

11. CHAIN OF CUSTODY:
- Evidence sealed by ${officerName} with HMAC digital stamp.

12. INVESTIGATION CONCLUSION:
Recommend formal trial prosecution and permanent freezing of Axis Bank ACC-9048-2819-5501.

Generated by ForensIQ System | Timestamp: ${new Date().toISOString()}
      `;

      const element = document.createElement('a');
      const file = new Blob([reportText], {
        type: 'text/plain',
      });

      element.href = URL.createObjectURL(file);
      element.download = `ForensIQ_Court_Report_${activeCase.id}.txt`;

      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);

      URL.revokeObjectURL(element.href);
    }, 1000);
  };

  const handlePrint = () => {
    window.print();
  };

  const copyReportSummary = () => {
    navigator.clipboard.writeText(
      `ForensIQ Court Report Summary for Case ${activeCase.id} - Officer ${officerName}`
    );

    setIsCopied(true);

    setTimeout(() => {
      setIsCopied(false);
    }, 2000);
  };

  return (
    <div className="space-y-8 animate-fadeIn">

      {/* TOP HEADER */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-slate-950 via-[#0b132a] to-slate-950 border border-slate-800 flex flex-col md:flex-row items-start md:items-center justify-between gap-6 shadow-2xl relative overflow-hidden">

        <div className="absolute top-0 right-0 w-96 h-96 bg-cyan-500/5 rounded-full blur-3xl pointer-events-none" />

        <div className="space-y-2 z-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 text-cyan-400 text-xs font-semibold border border-cyan-500/30 font-mono">
            <Scale className="w-3.5 h-3.5" />
            <span>Official Court-Admissible Dossier Engine</span>
          </div>

          <h1 className="text-2xl sm:text-3xl font-serif italic text-white tracking-tight">
            Court Report Generator
          </h1>

          <p className="text-xs text-slate-400 max-w-2xl font-sans">
            Auto-compiles complete evidentiary dossiers compliant with
            Section 65B of the Indian Evidence Act / BNS rules, featuring
            cryptographic SHA-256 hash validation and digital custody
            signatures.
          </p>
        </div>

        <div className="z-10 flex flex-wrap items-center gap-3 shrink-0">

          <button
            type="button"
            onClick={handleGeneratePDF}
            disabled={isGenerating}
            className="px-4 py-2.5 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white font-bold text-xs rounded-xl shadow-lg transition-all cursor-pointer flex items-center gap-2 border border-cyan-400/30 disabled:opacity-50"
          >
            {isGenerating ? (
              <Sparkles className="w-4 h-4 animate-spin text-cyan-200" />
            ) : (
              <FileCheck className="w-4 h-4" />
            )}

            <span>
              {isGenerating
                ? 'Compiling Dossier...'
                : 'Generate PDF Report'}
            </span>
          </button>

          <button
            type="button"
            onClick={handleDownload}
            disabled={isDownloading}
            className="px-4 py-2.5 bg-slate-900 hover:bg-slate-800 text-emerald-400 font-bold text-xs rounded-xl border border-emerald-500/40 shadow-md transition-all cursor-pointer flex items-center gap-2 disabled:opacity-50"
          >
            {isDownloading ? (
              <Download className="w-4 h-4 animate-bounce text-emerald-300" />
            ) : (
              <Download className="w-4 h-4" />
            )}

            <span>
              {isDownloading
                ? 'Preparing File...'
                : 'Download Report'}
            </span>
          </button>

          <button
            type="button"
            onClick={handlePrint}
            className="p-2.5 bg-slate-900 hover:bg-slate-800 text-slate-300 rounded-xl border border-slate-700 cursor-pointer transition-all"
            title="Print Document"
          >
            <Printer className="w-4 h-4" />
          </button>

        </div>
      </div>

      {/* CASE SELECTOR */}
      <div className="p-4 bg-slate-950 border border-slate-800 rounded-2xl flex flex-col md:flex-row items-stretch md:items-center justify-between gap-4 shadow-xl text-xs font-mono">

        <div className="flex items-center gap-3">
          <span className="text-slate-400 font-bold uppercase text-[11px] flex items-center gap-1.5 shrink-0">
            <FolderLock className="w-4 h-4 text-cyan-400" />
            Target Incident File:
          </span>

          <div className="relative flex-1 min-w-[240px]">
            <select
              value={selectedCaseId}
              onChange={(e) =>
                setSelectedCaseId(e.target.value)
              }
              className="w-full pl-3 pr-8 py-2 bg-slate-900 border border-slate-700 rounded-xl text-xs text-slate-200 focus:outline-none focus:border-cyan-500 font-mono appearance-none cursor-pointer"
            >
              {cases.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.id} — {c.title} ({c.victimName})
                </option>
              ))}
            </select>

            <ChevronDown className="w-4 h-4 text-slate-400 absolute right-3 top-2.5 pointer-events-none" />
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-4 text-slate-300">

          <label className="flex items-center gap-2 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={activeWatermark}
              onChange={(e) =>
                setActiveWatermark(e.target.checked)
              }
              className="rounded bg-slate-900 border-slate-700 text-cyan-500 focus:ring-cyan-500/20"
            />
            <span>Court Watermark</span>
          </label>

          <label className="flex items-center gap-2 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={includeChainOfCustody}
              onChange={(e) =>
                setIncludeChainOfCustody(e.target.checked)
              }
              className="rounded bg-slate-900 border-slate-700 text-cyan-500 focus:ring-cyan-500/20"
            />
            <span>Custody Logs</span>
          </label>

          <label className="flex items-center gap-2 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={includeAIConfidence}
              onChange={(e) =>
                setIncludeAIConfidence(e.target.checked)
              }
              className="rounded bg-slate-900 border-slate-700 text-cyan-500 focus:ring-cyan-500/20"
            />
            <span>AI ForensIQ Digest</span>
          </label>

        </div>
      </div>

      {/* DOCUMENT */}
      <div className="p-1 sm:p-4 bg-slate-950/80 rounded-2xl border border-slate-800 shadow-2xl flex justify-center">

        <div className="w-full max-w-4xl bg-[#090d16] border-2 border-slate-700/80 rounded-2xl p-6 sm:p-10 space-y-8 font-sans text-slate-200 relative overflow-hidden shadow-2xl print:bg-white print:text-black print:border-none print:shadow-none">

          {/* WATERMARK */}
          {activeWatermark && (
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none opacity-5 select-none rotate-[-30deg]">
              <span className="text-6xl sm:text-8xl font-black uppercase tracking-widest text-slate-400 font-serif">
                FORENSIQ OFFICIAL COURT DOSSIER
              </span>
            </div>
          )}

          {/* DOCUMENT HEADER */}
          <div className="border-b-2 border-cyan-500/40 pb-6 space-y-4">

            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">

              <div className="flex items-center gap-3">

                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan-600 to-blue-700 flex items-center justify-center text-white font-serif font-bold text-xl shadow-lg border border-cyan-300/30 shrink-0">
                  FIQ
                </div>

                <div>
                  <h1 className="text-2xl font-black tracking-widest text-white uppercase font-mono font-serif">
                    FORENSIQ
                  </h1>

                  <h2 className="text-sm font-bold text-cyan-400 tracking-wider uppercase font-mono">
                    CYBERCRIME INVESTIGATION REPORT
                  </h2>
                </div>

              </div>

              <div className="text-left sm:text-right font-mono text-xs space-y-1">

                <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded bg-slate-900 border border-slate-700 text-emerald-400 font-bold">
                  <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                  <span>SEC 65B IT ACT COMPLIANT</span>
                </div>

                <div className="text-slate-400 text-[11px]">
                  Generated:{' '}
                  {new Date().toLocaleDateString('en-US', {
                    year: 'numeric',
                    month: 'long',
                    day: 'numeric',
                  })}
                </div>

              </div>
            </div>

            {/* REQUIRED HEADER FIELDS */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 pt-4 font-mono text-xs bg-slate-900/90 p-4 rounded-xl border border-slate-800">

              <div>
                <span className="text-slate-500 uppercase text-[10px] block font-bold">
                  Case ID:
                </span>
                <strong className="text-cyan-300 font-bold text-sm">
                  {activeCase.id}
                </strong>
              </div>

              <div>
                <span className="text-slate-500 uppercase text-[10px] block font-bold">
                  Investigation Officer:
                </span>
                <strong className="text-white">
                  {officerName}
                </strong>
                <span className="text-slate-400 text-[11px] block">
                  Badge #{officerBadge} ({officerBureau})
                </span>
              </div>

              <div>
                <span className="text-slate-500 uppercase text-[10px] block font-bold">
                  Victim:
                </span>
                <strong className="text-blue-300">
                  {activeCase.victimName}
                </strong>
                <span className="text-slate-400 text-[11px] block">
                  {activeCase.victimContact ||
                    'Contact Verified'}
                </span>
              </div>

              <div>
                <span className="text-slate-500 uppercase text-[10px] block font-bold">
                  Crime Type:
                </span>
                <strong className="text-amber-300">
                  {activeCase.category}
                </strong>
              </div>

              <div>
                <span className="text-slate-500 uppercase text-[10px] block font-bold">
                  Incident Date:
                </span>

                <strong className="text-slate-200">
                  {incidentDate}
                </strong>
              </div>

              <div>
                <span className="text-slate-500 uppercase text-[10px] block font-bold">
                  Financial Loss Amount:
                </span>

                <strong className="text-rose-400 font-bold text-sm">
                  {activeCase.lossAmount ||
                    '₹25,000 (Loss Verified)'}
                </strong>
              </div>

            </div>
          </div>

          {/* SECTION 1 */}
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider font-mono flex items-center gap-2 border-b border-slate-800 pb-1.5">
              <span className="w-5 h-5 rounded bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-xs">
                1
              </span>
              Case Summary
            </h3>

            <div className="p-4 bg-slate-900/60 rounded-xl border border-slate-800/80 text-xs leading-relaxed text-slate-300 space-y-2 font-sans">
              <p>
                {activeCase.description ||
                  'This official investigation dossier addresses a high-volume financial cybercrime incident involving SMS phishing (smishing), unauthorized IMPS fund extraction, and identity spoofing targeting the complainant.'}
              </p>

              <p className="text-slate-400 font-mono text-[11px]">
                Modus Operandi: Malicious payload sent via
                spoofed SIM gateway routing victim to fake banking
                landing portal. Victim credentials intercepted and
                used to trigger unverified IMPS transaction.
              </p>
            </div>
          </div>

          {/* SECTION 2 */}
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider font-mono flex items-center gap-2 border-b border-slate-800 pb-1.5">
              <span className="w-5 h-5 rounded bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-xs">
                2
              </span>
              Victim Information
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 p-4 bg-slate-900/60 rounded-xl border border-slate-800/80 text-xs font-mono">

              <div className="space-y-1">
                <span className="text-slate-500 text-[10px] uppercase">
                  Full Legal Name:
                </span>
                <div className="text-white font-bold">
                  {activeCase.victimName}
                </div>
              </div>

              <div className="space-y-1">
                <span className="text-slate-500 text-[10px] uppercase">
                  Contact Handle:
                </span>
                <div className="text-cyan-300">
                  {activeCase.victimContact ||
                    'alex.rivera@example.com'}
                </div>
              </div>

              <div className="space-y-1">
                <span className="text-slate-500 text-[10px] uppercase">
                  Verification Status:
                </span>

                <div className="text-emerald-400 font-bold flex items-center gap-1">
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  ID Verified (Govt Portal Sync)
                </div>
              </div>

              <div className="space-y-1">
                <span className="text-slate-500 text-[10px] uppercase">
                  Device & Network Artifacts:
                </span>

                <div className="text-slate-300">
                  Apple iPhone 15 Pro (iOS 18.2) | Airtel Cellular
                  Data
                </div>
              </div>

            </div>
          </div>

          {/* SECTION 3 */}
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-rose-400 uppercase tracking-wider font-mono flex items-center gap-2 border-b border-slate-800 pb-1.5">
              <span className="w-5 h-5 rounded bg-rose-500/10 text-rose-400 flex items-center justify-center text-xs">
                3
              </span>
              Suspect Information
            </h3>

            <div className="p-4 bg-rose-950/20 rounded-xl border border-rose-500/30 space-y-3 text-xs font-mono">

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">

                <div>
                  <span className="text-slate-400 text-[10px] uppercase">
                    Primary Threat Actor:
                  </span>

                  <div className="text-rose-300 font-bold">
                    Suspect A (Vikram Malhotra)
                  </div>

                  <span className="text-slate-500 text-[10px]">
                    Alias: @ShadowOperator (Telegram)
                  </span>
                </div>

                <div>
                  <span className="text-slate-400 text-[10px] uppercase">
                    Mule Handler:
                  </span>

                  <div className="text-amber-300 font-bold">
                    Rajesh Kumar
                  </div>

                  <span className="text-slate-500 text-[10px]">
                    Axis Bank ACC-9048-2819-5501
                  </span>
                </div>

                <div>
                  <span className="text-slate-400 text-[10px] uppercase">
                    Threat Severity:
                  </span>

                  <div className="text-rose-400 font-bold uppercase">
                    Critical Syndicate Mastermind
                  </div>
                </div>

              </div>

              <div className="pt-2 border-t border-rose-500/20 text-slate-300 font-sans leading-relaxed text-[11px]">
                <strong>Forensic Profile:</strong> Operates an
                organized smishing network routing funds across
                multiple mule accounts in Mumbai and Delhi
                circles. IP host traced to TOR exit router
                185.220.101.5 (Frankfurt relay).
              </div>

            </div>
          </div>

          {/* SECTION 4 */}
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider font-mono flex items-center gap-2 border-b border-slate-800 pb-1.5">
              <span className="w-5 h-5 rounded bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-xs">
                4
              </span>
              Evidence List
            </h3>

            <div className="overflow-x-auto">
              <table className="w-full text-left font-mono text-xs border border-slate-800 rounded-xl overflow-hidden">
                <thead className="bg-slate-900 text-slate-400 uppercase text-[10px]">
                  <tr>
                    <th className="p-2.5">Evid ID</th>
                    <th className="p-2.5">Artifact Name</th>
                    <th className="p-2.5">Type / Category</th>
                    <th className="p-2.5">Custody Status</th>
                  </tr>
                </thead>

                <tbody className="divide-y divide-slate-800/60 bg-slate-950/60 text-slate-300">

                  <tr>
                    <td className="p-2.5 text-cyan-400 font-bold">
                      EVID-101
                    </td>
                    <td className="p-2.5 text-white">
                      SMS_Phishing_Payload_Screenshot.png
                    </td>
                    <td className="p-2.5 text-slate-400">
                      Smishing Link Artifact
                    </td>
                    <td className="p-2.5 text-emerald-400 font-bold">
                      Vault Sealed
                    </td>
                  </tr>

                  <tr>
                    <td className="p-2.5 text-cyan-400 font-bold">
                      EVID-102
                    </td>
                    <td className="p-2.5 text-white">
                      IMPS_Transaction_Receipt_TXN88492.pdf
                    </td>
                    <td className="p-2.5 text-slate-400">
                      Financial Ledger Export
                    </td>
                    <td className="p-2.5 text-emerald-400 font-bold">
                      Vault Sealed
                    </td>
                  </tr>

                  <tr>
                    <td className="p-2.5 text-cyan-400 font-bold">
                      EVID-103
                    </td>
                    <td className="p-2.5 text-white">
                      Network_PCAP_Headers_185.220.101.5.cap
                    </td>
                    <td className="p-2.5 text-slate-400">
                      Network Packet Capture
                    </td>
                    <td className="p-2.5 text-emerald-400 font-bold">
                      Vault Sealed
                    </td>
                  </tr>

                </tbody>
              </table>
            </div>
          </div>

          {/* SECTION 5 */}
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider font-mono flex items-center gap-2 border-b border-slate-800 pb-1.5">
              <span className="w-5 h-5 rounded bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-xs">
                5
              </span>
              Cryptographic SHA-256 Hash Verification
            </h3>

            <div className="p-4 bg-slate-900/90 rounded-xl border border-slate-800 space-y-2 font-mono text-xs">

              <div className="p-2.5 rounded bg-slate-950 border border-slate-800 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">

                <div className="truncate">
                  <span className="text-slate-500 text-[10px] block uppercase">
                    EVID-101 Hash Digest:
                  </span>

                  <code className="text-cyan-300 text-[11px]">
                    e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
                  </code>
                </div>

                <span className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 text-[10px] font-bold shrink-0">
                  IMMUTABLE
                </span>
              </div>

              <div className="p-2.5 rounded bg-slate-950 border border-slate-800 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">

                <div className="truncate">
                  <span className="text-slate-500 text-[10px] block uppercase">
                    EVID-102 Hash Digest:
                  </span>

                  <code className="text-cyan-300 text-[11px]">
                    7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284ddd200126d9069e
                  </code>
                </div>

                <span className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 text-[10px] font-bold shrink-0">
                  IMMUTABLE
                </span>
              </div>

            </div>
          </div>

          {/* SECTION 6 */}
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider font-mono flex items-center gap-2 border-b border-slate-800 pb-1.5">
              <span className="w-5 h-5 rounded bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-xs">
                6
              </span>
              Extracted Entities (NLP & OCR Parsed)
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3 font-mono text-xs">

              <div className="p-3 bg-slate-900/60 rounded-xl border border-slate-800 space-y-1">
                <span className="text-slate-500 text-[10px] uppercase flex items-center gap-1">
                  <Phone className="w-3 h-3 text-cyan-400" />
                  Phone Number:
                </span>

                <strong className="text-cyan-300">
                  +91 98765 43210
                </strong>

                <span className="text-slate-400 text-[10px] block">
                  Burner SMS Sender ID
                </span>
              </div>

              <div className="p-3 bg-slate-900/60 rounded-xl border border-slate-800 space-y-1">
                <span className="text-slate-500 text-[10px] uppercase flex items-center gap-1">
                  <Receipt className="w-3 h-3 text-amber-400" />
                  UPI VPA Target:
                </span>

                <strong className="text-amber-300">
                  paym-fraudster@okaxis
                </strong>

                <span className="text-slate-400 text-[10px] block">
                  Axis Bank Virtual Handle
                </span>
              </div>

              <div className="p-3 bg-slate-900/60 rounded-xl border border-slate-800 space-y-1">
                <span className="text-slate-500 text-[10px] uppercase flex items-center gap-1">
                  <CreditCard className="w-3 h-3 text-emerald-400" />
                  Mule Account:
                </span>

                <strong className="text-emerald-300">
                  ACC-9048-2819-5501
                </strong>

                <span className="text-slate-400 text-[10px] block">
                  Holder: Rajesh Kumar
                </span>
              </div>

              <div className="p-3 bg-slate-900/60 rounded-xl border border-slate-800 space-y-1">
                <span className="text-slate-500 text-[10px] uppercase flex items-center gap-1">
                  <Globe className="w-3 h-3 text-rose-400" />
                  Host IP Node:
                </span>

                <strong className="text-rose-300">
                  185.220.101.5
                </strong>

                <span className="text-slate-400 text-[10px] block">
                  TOR Router (Frankfurt)
                </span>
              </div>

              <div className="p-3 bg-slate-900/60 rounded-xl border border-slate-800 space-y-1">
                <span className="text-slate-500 text-[10px] uppercase flex items-center gap-1">
                  <Mail className="w-3 h-3 text-purple-400" />
                  Contact Email:
                </span>

                <strong className="text-purple-300">
                  suspect_x@shadowpay.io
                </strong>

                <span className="text-slate-400 text-[10px] block">
                  Spoofed Mailgun Relay
                </span>
              </div>

            </div>
          </div>

          {/* SECTION 7 */}
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider font-mono flex items-center gap-2 border-b border-slate-800 pb-1.5">
              <span className="w-5 h-5 rounded bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-xs">
                7
              </span>
              Chronological Investigation Timeline
            </h3>

            <div className="p-4 bg-slate-900/60 rounded-xl border border-slate-800 space-y-3 font-mono text-xs">

              <div className="flex items-start gap-3">
                <div className="w-2 h-2 rounded-full bg-cyan-400 mt-1.5 shrink-0" />
                <div>
                  <strong className="text-white">
                    2026-08-04 14:32:00 UTC
                  </strong>

                  <p className="text-slate-400 font-sans text-[11px]">
                    Victim Alex Rivera filed official cybercrime
                    complaint following unauthorized IMPS transfer.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="w-2 h-2 rounded-full bg-indigo-400 mt-1.5 shrink-0" />

                <div>
                  <strong className="text-white">
                    2026-08-04 15:10:00 UTC
                  </strong>

                  <p className="text-slate-400 font-sans text-[11px]">
                    Evidence uploaded and auto-hashed with SHA-256
                    signature chain.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="w-2 h-2 rounded-full bg-rose-400 mt-1.5 shrink-0" />

                <div>
                  <strong className="text-white">
                    2026-08-05 09:30:00 UTC
                  </strong>

                  <p className="text-slate-400 font-sans text-[11px]">
                    ForensIQ cross-case correlation flagged matching
                    Phone +91 98765 43210 in Case #1089.
                  </p>
                </div>
              </div>

            </div>
          </div>

          {/* SECTION 8 */}
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider font-mono flex items-center gap-2 border-b border-slate-800 pb-1.5">
              <span className="w-5 h-5 rounded bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-xs">
                8
              </span>
              ForensIQ AI Intelligence & Risk Breakdown
            </h3>

            <div className="p-4 bg-slate-900/90 rounded-xl border border-slate-800 space-y-3 text-xs font-mono">

              <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                <span className="text-slate-400">
                  AI Threat Confidence Index:
                </span>

                <span className="px-2.5 py-1 rounded bg-rose-500/20 text-rose-300 font-bold border border-rose-500/40">
                  98.4% HIGH CONFIDENCE FRAUD
                </span>
              </div>

              <p className="text-slate-300 font-sans leading-relaxed text-[11px]">
                Machine intelligence pattern analysis verifies high
                similarity with known smishing campaigns targeting
                private banking apps. Automated recommendations
                include immediate account freezing and Section 91
                CrPC notice issuance.
              </p>

            </div>
          </div>

          {/* SECTION 9 */}
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider font-mono flex items-center gap-2 border-b border-slate-800 pb-1.5">
              <span className="w-5 h-5 rounded bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-xs">
                9
              </span>
              Related Correlated Cases
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 font-mono text-xs">

              <div className="p-3 bg-slate-900/60 rounded-xl border border-slate-800 flex items-center justify-between">
                <div>
                  <strong className="text-amber-300 font-bold">
                    Case #1089
                  </strong>
                  <p className="text-slate-400 text-[10px]">
                    Phishing & Identity Theft
                  </p>
                </div>

                <span className="text-slate-500 text-[10px]">
                  Shared Sender SIM
                </span>
              </div>

              <div className="p-3 bg-slate-900/60 rounded-xl border border-slate-800 flex items-center justify-between">
                <div>
                  <strong className="text-amber-300 font-bold">
                    Case #2048
                  </strong>
                  <p className="text-slate-400 text-[10px]">
                    Investment Fraud Syndicate
                  </p>
                </div>

                <span className="text-slate-500 text-[10px]">
                  Shared Mule Account
                </span>
              </div>

            </div>
          </div>

          {/* SECTION 10 */}
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider font-mono flex items-center gap-2 border-b border-slate-800 pb-1.5">
              <span className="w-5 h-5 rounded bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-xs">
                10
              </span>
              Applicable Statutory & Legal Sections
            </h3>

            <div className="p-4 bg-slate-900/60 rounded-xl border border-slate-800 space-y-2 font-mono text-xs">

              <div className="flex items-start gap-2 text-slate-200">
                <Scale className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />

                <div>
                  <strong className="text-white">
                    Section 66D Information Technology Act, 2000:
                  </strong>

                  <p className="text-slate-400 font-sans text-[11px]">
                    Punishment for cheating by personation by using
                    computer resource (up to 3 years imprisonment).
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-2 text-slate-200 pt-2 border-t border-slate-800">
                <Scale className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />

                <div>
                  <strong className="text-white">
                    Section 66C Information Technology Act, 2000:
                  </strong>

                  <p className="text-slate-400 font-sans text-[11px]">
                    Punishment for identity theft and fraudulent
                    electronic signatures.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-2 text-slate-200 pt-2 border-t border-slate-800">
                <Scale className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />

                <div>
                  <strong className="text-white">
                    BNS Section 318(4) / IPC Section 420:
                  </strong>

                  <p className="text-slate-400 font-sans text-[11px]">
                    Cheating and dishonestly inducing delivery of
                    property.
                  </p>
                </div>
              </div>

            </div>
          </div>

          {/* SECTION 11 */}
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider font-mono flex items-center gap-2 border-b border-slate-800 pb-1.5">
              <span className="w-5 h-5 rounded bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-xs">
                11
              </span>
              Chain of Custody Ledger
            </h3>

            {includeChainOfCustody && (
              <div className="p-4 bg-slate-900/60 rounded-xl border border-slate-800 space-y-2 font-mono text-xs">

                <div className="flex items-center justify-between text-slate-300">
                  <span>
                    Ingest Handler:{' '}
                    <strong>
                      {officerName} ({officerBadge})
                    </strong>
                  </span>

                  <span className="text-emerald-400">
                    HMAC-SHA256 Signed
                  </span>
                </div>

                <div className="text-[11px] text-slate-400 font-sans">
                  Evidence was ingested through secure TLS 1.3
                  encrypted vault tunnel. Cryptographic proof sealed
                  immediately upon receipt to prevent alteration
                  prior to trial proceedings.
                </div>

              </div>
            )}
          </div>

          {/* SECTION 12 */}
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider font-mono flex items-center gap-2 border-b border-slate-800 pb-1.5">
              <span className="w-5 h-5 rounded bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-xs">
                12
              </span>
              Investigation Conclusion & Endorsement
            </h3>

            <div className="p-4 bg-slate-900/90 rounded-xl border border-slate-800 space-y-4 text-xs font-sans">

              <p className="text-slate-200 leading-relaxed">
                Based on forensic digital evidence, cryptographic
                hash verification, and threat actor network mapping,
                it is concluded that Case #{activeCase.id} represents
                an intentional financial cyber-extortion scheme.
                Immediate trial prosecution under Section 66D IT Act
                and permanent freezing of Axis Bank
                ACC-9048-2819-5501 is strongly recommended.
              </p>

              <div className="pt-6 border-t border-slate-800 flex flex-col sm:flex-row items-start sm:items-end justify-between gap-6 font-mono">

                <div className="space-y-1">

                  <div className="w-48 border-b border-slate-600 pb-1 italic font-serif text-cyan-300">
                    {officerName}
                  </div>

                  <span className="text-slate-500 text-[10px] uppercase block font-bold">
                    Investigating Officer Digital Signature
                  </span>

                  <span className="text-slate-400 text-[10px]">
                    Badge #{officerBadge} | {officerBureau}
                  </span>

                </div>

                <div className="flex items-center gap-3 bg-slate-950 p-2.5 rounded-xl border border-slate-800">

                  <QrCode className="w-10 h-10 text-cyan-400 shrink-0" />

                  <div className="text-[10px] space-y-0.5 text-slate-400">

                    <strong className="text-white block">
                      VERIFY DOSSIER INTEGRITY
                    </strong>

                    <span>
                      Ledger ID: FIQ-COURT-2026-X99
                    </span>

                    <span className="block text-emerald-400">
                      Status: Officially Endorsed
                    </span>

                  </div>

                </div>

              </div>
            </div>
          </div>

          {/* FOOTER */}
          <div className="pt-6 border-t border-slate-800 flex flex-col sm:flex-row items-center justify-between text-[10px] font-mono text-slate-500 gap-2">
            <span>
              FORENSIQ CYBERCRIME BUREAU © 2026 — OFFICIAL LEGAL
              DOCUMENT
            </span>

            <span>
              PAGE 1 OF 1 — CONFIDENTIAL JUDICIAL DOSSIER
            </span>
          </div>

        </div>
      </div>
    </div>
  );
};