import {
  CaseItem,
  User,
  NotificationItem,
  AuditLogItem,
  ThreatFeedItem,
} from './types';

/**
 * ForensIQ initial application state.
 *
 * Phase 1:
 *
 * - No fabricated investigation records.
 * - No fake victims or officers.
 * - No fake evidence.
 * - No fabricated threat intelligence.
 * - No simulated audit history.
 *
 * All records will be created through actual application actions.
 *
 * The application uses the backend/database as the persistent
 * source of truth.
 */

/* -------------------------------------------------------------------------- */
/* USERS                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * No users are pre-created.
 *
 * Users will be created through the registration flow.
 *
 * Keeping this empty prevents the application from presenting
 * fabricated identities as real users.
 */
export const INITIAL_USERS: Record<string, User> = {};

/* -------------------------------------------------------------------------- */
/* CASES                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * No cases are pre-created.
 *
 * Cases will be created through the complaint/case filing workflow.
 */
export const INITIAL_CASES: CaseItem[] = [];

/* -------------------------------------------------------------------------- */
/* NOTIFICATIONS                                                              */
/* -------------------------------------------------------------------------- */

/**
 * Notifications are generated by actual application events.
 *
 * Examples:
 * - Case submitted
 * - Evidence uploaded
 * - Case assigned
 * - Evidence verified
 * - Case status changed
 * - AI analysis completed
 */
export const INITIAL_NOTIFICATIONS: NotificationItem[] = [];

/* -------------------------------------------------------------------------- */
/* AUDIT LOGS                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Audit logs are generated when users perform important actions.
 *
 * Examples:
 * - Login
 * - Logout
 * - Case creation
 * - Evidence upload
 * - Evidence verification
 * - Case assignment
 * - Report generation
 * - AI forensic analysis
 */
export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [];

/* -------------------------------------------------------------------------- */
/* THREAT FEED                                                                */
/* -------------------------------------------------------------------------- */

/**
 * No fabricated live threat intelligence is displayed.
 *
 * A real threat-intelligence feed can be connected in a later phase.
 */
export const INITIAL_THREAT_FEED: ThreatFeedItem[] = [];